<?php
$params = $this->getParams();
if (isset($params['mensagem'])) {
    echo "<div class=\"row\">
        <div class=\"alert alert-dark\" role=\"alert\">
          {$params['mensagem']}
        </div>
</div>";
}
?>

<form action="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Imposto&acao=insertOrUpdate" method="post">
    <div class="form-row">
        <input hidden name="id" value="<?php echo $params['dados']['id'] ?>" readonly>
        <div class="form-group col-md-6">
            <label for="descricao">Descrição</label>
            <input type="text" class="form-control" name="descricao" id="descricao" value="<?php echo $params['dados']['descricao'] ?>">
        </div>
        <div class="form-group col-md-6">
            <label for="porcentagem">Porcentagem</label>
            <input type="text" class="form-control" name="porcentagem" id="porcentagem" value="<?php echo $params['dados']['porcentagem'] ?>">
        </div>
    </div>
    <a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Imposto&acao=index" class="btn btn-link btn-sm">Voltar</a>
    <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
</form>