<?php
$controller = "Imposto";
$params = $this->getParams();
?>

<div class="row p-2">
    <a class="btn btn-outline-primary btn-sm" href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=<?php echo $controller ?>&acao=insertOrUpdate">Adicionar</a>
</div>
<?php if (count($params) <= 0) { ?>
    <div class="row">
        <div class="alert alert-warning" role="alert">
            A simple warning alert—check it out!
        </div>
    </div>
<?php } else { ?>
    <table class="table">
        <thead>
        <tr>
            <th>Descrição</th>
            <th>Porcentagem</th>
            <th colspan="2" scope="col">Ações</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($params['data'] as $data) {
            echo "<tr>";
            echo "<td>{$data['descricao']}</td>";
            echo "<td>{$data['porcentagem']}</td>";
            echo "<td><a href='http://{$_SERVER['HTTP_HOST']}/?controle={$controller}&acao=insertOrUpdate&id={$data['id']}'>Editar</a></td>";
            echo "<td><a href='http://{$_SERVER['HTTP_HOST']}/?controle={$controller}&acao=delete&id={$data['id']}'>Deletar</a></td>";
            echo "</tr>";
        } ?>

        </tbody>
    </table>
<?php } ?>
