<?php
$controller = 'ProductTypes';
$params = $this->getParams();

if (isset($params['return'])) {
    echo "<div class=\"row\">
        <div class=\"alert alert-{$params['return']['status']} w-100 d-flex justify-content-center\" role=\"alert\">
          {$params['return']['message']}
        </div>
</div>";
}
?>

<form action="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=<?php echo $controller ?>&acao=insertOrUpdate" method="post">
    <div class="form-row">
        <input hidden name="id" value="<?php echo $params['data']['id'] ?>" readonly>
        <div class="form-group col-md-6">
            <label for="description">Descrição</label>
            <input type="text" class="form-control" name="description" id="description" value="<?php echo $params['data']['description'] ?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="taxes">Impostos</label>
            <select id="taxes" data-ids="<?php echo $params['data']['taxid'] ?>" class="select2-multiple js-states form-control" name="taxes[]" multiple="multiple">
            </select>
        </div>
    </div>
    <a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=<?php echo $controller ?>&acao=index" class="btn btn-link btn-sm">Voltar</a>
    <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
</form>

<script>
    $(document).ready(function() {
        $('.select2-multiple').select2({
            ajax: {
                url: 'http://<?php echo $_SERVER["HTTP_HOST"] ?>/?controle=Taxes&acao=json',
                dataType: 'json',
                processResults: function (data) {
                    let result = [];
                    for (let i in data) {
                        result.push({
                            "id": data[i].id,
                            "text": data[i].description
                        });
                    }

                    return {
                        results: result
                    };
                }
            },
            allowClear: true,
            language: "pt-br",
            placeholder: "Selecione o(s) imposto(s)",
        });
    });
</script>
