<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mercadinho</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="row">
    <div class="col-3 p-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Index&acao=index" role="tab"
               aria-controls="v-pills-home" aria-selected="true">Venda</a>
            <a class="nav-link" href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Imposto&acao=index" role="tab"
               aria-controls="v-pills-profile" aria-selected="false">Impostos</a>
            <a class="nav-link" href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=TipoProdutos&acao=index" role="tab"
               aria-controls="v-pills-messages" aria-selected="false">Tipo de Produtos</a>
            <a class="nav-link" href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Produtos&acao=index" role="tab"
               aria-controls="v-pills-settings" aria-selected="false">Produtos</a>
        </div>
    </div>
    <div class="col-9 p-2">
        <div class="container">
            <?php include($pageView) ?>
        </div>
    </div>

</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script>
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        console.log("opa");
        e.target // newly activated tab
        e.relatedTarget // previous active tab
    })
</script>
</body>
</html>