<?php
$params = $this->getParams();
if (isset($params['return'])) {
    echo "<div class=\"row\">
        <div class=\"alert alert-{$params['return']['status']} w-100 d-flex justify-content-center\" role=\"alert\">
          {$params['return']['message']}
        </div>
</div>";
}
?>

<form action="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Taxes&acao=insertOrUpdate" method="post">
    <div class="form-row">
        <input hidden name="id" value="<?php echo $params['data']['id'] ?>" readonly>
        <div class="form-group col-md-6">
            <label for="description">Descrição</label>
            <input type="text" class="form-control" name="description" id="description" value="<?php echo $params['data']['description'] ?>">
        </div>
        <div class="form-group col-md-6">
            <label for="percentage">Porcentagem</label>
            <input type="text" class="form-control" name="percentage" id="percentage" value="<?php echo $params['data']['percentage'] ?>">
        </div>
    </div>
    <a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=Taxes&acao=index" class="btn btn-link btn-sm">Voltar</a>
    <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
</form>