<?php
$controller = 'ProductTypes';
$params = $this->getParams();

if (isset($params['return'])) {
    echo "<div class=\"row\">
        <div class=\"alert alert-{$params['return']['status']} w-100 d-flex justify-content-center\" role=\"alert\">
          {$params['return']['message']}
        </div>
</div>";
}

$productTypeId = $params['data']['id'];
$productTypeIdParam = "";
if (isset($productTypeId) && !empty($productTypeId)) {
    $productTypeIdParam = "&id={$productTypeId}";
}
?>

<form action="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=<?php echo $controller ?>&acao=insertOrUpdate<?php echo $productTypeIdParam ?>" method="post">
    <div class="form-row">
        <input hidden name="id" value="<?php echo $productTypeId ?>" readonly>
        <div class="form-group col-md-6">
            <label for="description">Descrição</label>
            <input type="text" class="form-control" name="description" id="description" value="<?php echo $params['data']['description'] ?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="taxes">Impostos</label>
            <select id="taxes" class="select2-multiple js-states form-control" name="taxes[]" multiple="multiple"></select>
        </div>
    </div>
    <a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/?controle=<?php echo $controller ?>&acao=index" class="btn btn-link btn-sm">Voltar</a>
    <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
</form>

<script>
    $(document).ready(function() {
        $.ajax({
            url: 'http://<?php echo $_SERVER["HTTP_HOST"] ?>/?controle=Taxes&acao=json&id=<?php echo $productTypeId ?>',
            dataType: 'json',
        })
        .done(function( data ) {
            let options = '';
            for (let i in data['all']) {
                let selected = data['selected'].includes(data['all'][i].id) ? 'selected' : '';
                options += '<option '+ selected +' value="' + data['all'][i].id + '">' + data['all'][i].description + '</option>';
            }
            $('#taxes').append(options);

            $('.select2-multiple').select2({
                allowClear: true,
                language: "pt-br",
                placeholder: "Selecione o(s) imposto(s)",
            });
        });
    });
</script>
